name: Just for test

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@master

      - name: Check versions
        id: check
        run: |
            v1=$(curl https://test.pypi.org/pypi/libasterix/json | jq '.info | .version')
            echo "Published version: $v1"

            v2=$(cat libs/python/pyproject.toml | grep "^version" | sed -e 's/version = //')
            echo "Current version: $v2"

            if [ "$v1" != "$v2" ]; then
                echo "update=proceed" | tee -a "$GITHUB_OUTPUT";
            else
                echo "update=skip" | tee -a "$GITHUB_OUTPUT";
            fi

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Test
        run: |
            echo ${{ needs.release-build.steps.check.outputs }}
            echo ${{ needs.release-build.steps.check.outputs.update }}
            echo ${{ needs.release-build.steps.check.outputs.update == 'proceed' }}

