name: Just for test 2

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@master

      - name: Check versions
        id: step1
        run: echo "result=hello" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Test
      - run: echo "Job 1 output: ${{ needs.job1.outputs.output1 }}"

