name: Test 2

on:
  workflow_dispatch: {}

jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      runner-name: ${{ steps.runner.outputs.name }}
    steps:
      - name: Set runner name
        id: runner
        run: |
          echo "name=ubuntu-latest" >> $GITHUB_OUTPUT
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Show job-1 output
        run: |
          echo "Output job-1: ${{ needs.job-1.outputs.runner-name}}"

